# permissions for end users to edit sidecars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecar-editor-role
rules:
- apiGroups:
  - side.sidecar.com
  resources:
  - sidecars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - side.sidecar.com
  resources:
  - sidecars/status
  verbs:
  - get
